### ISSUE TITLE
Being able to bind Media control keys on the keyboard to the program

### ISSUE THREAD

**Issue by TechnoManiac98** [justinknguyen/BeatBind#1]
**Is your feature request related to a problem? Please describe.**
Not a problem but a small inconvinience for people who already have media controls on their keyboards like Corsair K95 and Razor Huntsman

**Describe the solution you'd like**
Media keys already present on many keyboards can be used as 1 button binds but the program fails to register media keys for keybinds, this includes Play/Pause, stop, next /prev track and Volume roller/dial/bittons.

**Describe alternatives you've considered**
for now i used AHK to make a workaround to this by binding keyboard media keys to the shortcuts bound in the program but its yet another process running in the bg..

**Additional context**
Would really appreciate if you could honor this feature request, was looking for a program like this for the longest time and 90% perfect the way it is. i want to thank you for taking the effort to make something like this!

**Comment by justinknguyen** [comment]
no problem at all! I can get this done for you quickly today :)

**Comment by justinknguyen** [comment]
v1.0.1 is able to register multimedia keys, but there's a problem. The multimedia keys are global hotkeys handled by Windows, so when you press a media key, it sends a command to the operating system, which then passes it on to the appropriate application. It's another layer on top of this app, so they'll end up canceling each other out (Windows media functions will trigger, then this app will trigger). Nevertheless, I still added the functionality to the app for you to maybe figure something out other than an AHK running.

Sorry there isn't a cleaner solution to an AHK or rebinding your multimedia keys. I'll keep this issue open and see if I can think of a solution.

**Comment by TechnoManiac98** [comment]
> 

yes it is and i made it work using icue software (corsair keyboards) and its working flawlessly!
