### ISSUE TITLE
Settings are not saved on PC startup

### ISSUE THREAD

**Issue by Jacob-Lasky** [justinknguyen/BeatBind#10]
**Describe the bug**
Each morning that I turn on my PC, the BeatBind window pops up and I must redo all of my settings including the client ID and device ID, as if starting BeatBind for the first time.

**To Reproduce**
Add the client ID, client secret, click on get devices and select my device. Then I unselect 'shift' in the modifiers for play/pause, previous track and next track. Then I update the play/pause key to be 'up'. Then I check 'start on windows startup' and 'start minimized'. Then I click 'save' and then I click 'start & close'.

**Expected behavior**
I expect my settings to save.

**Desktop (please complete the following information):**
 - OS: Windows 11 Home, 22H2, Build 22621.3155
 - Version 1.3.0

**Comment by justinknguyen** [comment]
where are you keeping the BeatBind folder? If you're keeping it inside your Program Files folder then it needs to be ran in admin mode to be able to save and write files. I recommend placing it somewhere else

**Comment by Jacob-Lasky** [comment]
AH! That was it. I moved it from Program Files to a different folder and it has been fixed. Thanks for the prompt response!
