### ISSUE TITLE
Server listening on localhost has not been accessed error

### ISSUE THREAD

**Issue by GOOSLI** [justinknguyen/BeatBind#12]
- I filled the ClientID, ClientSecret and Port fields according to the [instruction](https://github.com/justinknguyen/BeatBind?tab=readme-ov-file#client-id-client-secret-and-port)
- After clicking Get Devices button the browser opens and I receive the following error in a few seconds.

![BeatBind_UMx9jsFVhv](https://github.com/justinknguyen/BeatBind/assets/29120562/7b8c0386-ae60-4245-85d7-2c90cd9350ff)

In the browser I receive an error: ERR_CONNECTION_REFUSED

I've tried several different free ports but the problem remains. Also I've tried running Chrome in safe mode but that didn't helped.

 - OS:  Windows 10
 - Version 1.3.0

**Comment by GOOSLI** [comment]
I ve managed to fix this problem:
1) Opened the port in the firewall
2) Clicked GetDevices button
3) Copied the url from the Chrome when it opened before showing the error
4) Closed the error message and closed the browser
5) Clicked GetDevices button again and rapidly closed the browser before the page loaded
6) The BeatBind application frozen at that moment
7) Pasted the url into Chrome in a **safe mode**

Seemed like Chrome was redirecting from http to https by default

**Comment by GOOSLI** [comment]
Isn't it possible to make the application listening the https callback?

**Comment by justinknguyen** [comment]
Glad you managed to figure it out, but sorry you had to go through all that haha it should just work. I haven't seen that error yet, and I'm not too sure how to reproduce that.

> Isn't it possible to make the application listening the https callback?
I'm not sure, I'll have to look into it when I have time, but the reason it's http is because that's what Spotify's examples were using https://developer.spotify.com/documentation/web-api/concepts/apps

**Comment by justinknguyen** [comment]
@GOOSLI I added `BeatBind-https.zip` to the release. Let me know if that fixes anything for you https://github.com/justinknguyen/BeatBind/releases/download/v1.3.0/BeatBind-https.zip

**Comment by GOOSLI** [comment]
Thank you for the response (and also thank you a lot for an application ❤️)! 

I've checked the `BeatBind-https.zip`, but behaviour didn't changed a lot. Now BeatBind application doesn't show an error, but nothing happens and browser shows ERR_CONNECTION_REFUSED

**Comment by justinknguyen** [comment]
> Thank you for the response (and also thank you a lot for an application ❤️)!
> 
> I've checked the `BeatBind-https.zip`, but behaviour didn't changed a lot. Now BeatBind application doesn't show an error, but nothing happens and browser shows ERR_CONNECTION_REFUSED

hmm and I’m guessing you’ve already set the Redirect URI on the Spotify app to include https?

**Comment by GOOSLI** [comment]
Like that?

![image](https://github.com/justinknguyen/BeatBind/assets/29120562/8a01db3e-bcd3-4bb8-9385-dc9189085754)

**Comment by justinknguyen** [comment]
> I did like that. Is that correct?
> 
> ![image](https://private-user-images.githubusercontent.com/29120562/311208990-8a01db3e-bcd3-4bb8-9385-dc9189085754.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMTA2NjgsIm5iZiI6MTcxMDAxMDM2OCwicGF0aCI6Ii8yOTEyMDU2Mi8zMTEyMDg5OTAtOGEwMWRiM2UtYmNkMy00YmI4LTkzODUtZGM5MTg5MDg1NzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDE4NTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhYTIwNmM0MmVlZmVkNDc3MGVhOTdkMDlkNTY2NmI3YWNjZjZhNjVhOGNjNDE2ZDc4MDJlNDBmZGFmMzE0MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PhjgyhOeKTXmM2fHcobR6CAuGw-aTAPjLnBNXW3rHNU)

Yea, just testing it myself and it looks like the callback can't be https

**Comment by GOOSLI** [comment]
Also FYI I've found out that HSTS setting for localhost in my browser for some reason was turned on and was permanently redirecting me to https. Top answer from [here](https://superuser.com/questions/565409/how-to-stop-an-automatic-redirect-from-http-to-https-in-chrome) solved my problem and I excluded localhost from HSTS. So maybe you can put it in FAQ section.

**Comment by justinknguyen** [comment]
> Also FYI I've found out that HSTS setting for localhost in my browser for some reason was turned on and was permanently redirecting me to https. Top answer from [here](https://superuser.com/questions/565409/how-to-stop-an-automatic-redirect-from-http-to-https-in-chrome) solved my problem and I excluded localhost from HSTS. So maybe you can put it in FAQ section.

Awesome! Thanks for letting me know, and I'll add that to the FAQ for sure. Thank you
