### ISSUE TITLE
Rewind song instead of going to previous one

### ISSUE THREAD

**Issue by ChrisKJM** [justinknguyen/BeatBind#14]
Back when I used Toastify, I sometimes utilised the option to go to the beginning of a song by pressing the "previous song" keybind (it would rewind to the start if more than 3 seconds of the song have elapsed, and go to the previous song otherwise).

I noticed that in this app this isn't a thing, so my feature request is to add that as a toggleable setting.

**Comment by justinknguyen** [comment]
Thanks for the contribution!

https://github.com/justinknguyen/BeatBind/releases/tag/v1.5.0
