### ISSUE TITLE
Prevent/hijack key propagation

### ISSUE THREAD

**Issue by liekki** [justinknguyen/BeatBind#16]
First off, thanks for the project, I've been looking for a working Toastify replacement for a while now!

**Is your feature request related to a problem? Please describe.**
I've used Ctrl+Shift+Z/X/C/V/B for global multimedia controls ever since WinAmp (and later Toastify) and while I'm able to use these with BeatBind as well, I quickly noticed that the hotkeys "leak" or get propagated and for example in Chrome whenever I CTRL+SHIFT+C to pause my song, the Chrome Dev Tools start inspecting and CTRL+SHIFT+B brings up the bookmarks bar.

**Describe the solution you'd like**
Make the hotkey "neutral" or somehoe stop the keypresses from being propagated. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by justinknguyen** [comment]
This app uses the `global_hotkeys` module by btsdev: https://github.com/btsdev/global_hotkeys. I recommend creating this issue ticket there so they can solve your issue. 

A side note, I just updated the global_hotkey module in BeatBind with [v1.5.2](https://github.com/justinknguyen/BeatBind/releases/tag/v1.5.2), but I think your issue still remains.

**Comment by justinknguyen** [comment]
closed due to inactivity

**Comment by justinknguyen** [comment]
@liekki this has officially been resolved with v2.0.1, please test it out! https://github.com/justinknguyen/BeatBind/releases/tag/v2.0.1

**Comment by liekki** [comment]
Thanks for the update and happy new year! I will test this later today

**Comment by justinknguyen** [comment]
Thanks and happy new year to you too!
