### ISSUE TITLE
Windows Key (Win+<key>)

### ISSUE THREAD

**Issue by cyraid** [justinknguyen/BeatBind#19]
**Describe the solution you'd like**
Being able to use Windows key to hold in as you push another key instead of ctrl/shift/alt. So, win+ins for play/pause for example.

**Describe alternatives you've considered**
Mapping some keys to those shortcut keys available like win+ins with autokey to ctrl+shift+alt p etc. But too much indirection.

**Comment by justinknguyen** [comment]
Sorry for the wait, just had some time and released v1.6.0 https://github.com/justinknguyen/BeatBind/releases/tag/v1.6.0

Please let me know if you find any bugs, thanks!

**Comment by cyraid** [comment]
@justinknguyen Just wanted to say thanks man.

**Comment by cyraid** [comment]
@justinknguyen maybe not possible, but is there a "stop" in the API? Cause sometimes I like to quickly walk away from the PC and used to hitting win+end to make sure it stops (whether it's playing or not). If not that's alright, awesome work so far.

**Comment by justinknguyen** [comment]
> @justinknguyen maybe not possible, but is there a "stop" in the API? Cause sometimes I like to quickly walk away from the PC and used to hitting win+end to make sure it stops (whether it's playing or not). If not that's alright, awesome work so far.

by "stop" do you mean you want it to stop listening for key presses, or just to pause the music?

**Comment by cyraid** [comment]
@justinknguyen just something that's guaranteed to pause with that key so I know it's not gonna play if I hit it, but just pause.

**Comment by justinknguyen** [comment]
> @justinknguyen just something that's guaranteed to pause with that key so I know it's not gonna play if I hit it, but just pause.

I see, no problem, I can add another hotkey field for just pausing. I'll let you know whenever I have some time :)

**Comment by cyraid** [comment]
@justinknguyen thanks a bunch man! Take it easy when you can too eh?

**Comment by justinknguyen** [comment]
> @justinknguyen thanks a bunch man! Take it easy when you can too eh?

I created separate Play and Pause hotkeys in v1.7.0 https://github.com/justinknguyen/BeatBind/releases/tag/v1.7.0

I refactored a lot of the code, so let me know if you notice any bugs. Thanks!

**Comment by cyraid** [comment]
@justinknguyen the new version wiped my previous settings when I launched it, but I just put the information back in, and seems to keep on relaunch after setting my settings again. Looks like all the keys work for me! Thanks again!

**Comment by justinknguyen** [comment]
> @justinknguyen the new version wiped my previous settings when I launched it, but I just put the information back in, and seems to keep on relaunch after setting my settings again. Looks like all the keys work for me! Thanks again!

no worries, and check out the [How Do I Update The App?](https://github.com/justinknguyen/BeatBind?tab=readme-ov-file#how-do-i-update-the-app) section to keep your settings for next time
