### ISSUE TITLE
Play/Pause not working

### ISSUE THREAD

**Issue by Iowerth** [justinknguyen/BeatBind#20]
Hi. Firstly, thanks for this amazing app! I used to use Toastify a couple of years, but...

Windows 10 x64. I have noticed that the Play/Pause option does not work no matter what keybinding is set. While other options work fine. Is it a bug or specific PC issue?
![1](https://github.com/user-attachments/assets/aa4837c9-a238-44ad-83e1-f3f52d7d4d5e)

**Comment by justinknguyen** [comment]
Hey, sorry you're having some trouble with it. That's definitely not supposed to happen. Can you send a screenshot of your config file `beatbind-config.json`? It's located in the same folder

**Comment by Iowerth** [comment]
![2](https://github.com/user-attachments/assets/666896f2-26bc-4250-bf27-a3da78e085a8)
I already changed some hotkeys.
Ofc I pressed "Start & Close". All hotkeys work fine except for "Play/Pause".

**Comment by Iowerth** [comment]
![2](https://github.com/user-attachments/assets/2ca2dd7d-9922-4004-b08f-593d17d45fad)
I already changed some hotkeys.
Ofc I pressed "Start & Close". All hotkeys work fine except for "Play/Pause".

**Comment by justinknguyen** [comment]
@Iowerth unfortunately, I'm not able to reproduce this bug, even copying your settings. However, I created a new release here to add logging to help debug this bug: https://github.com/justinknguyen/BeatBind/releases/tag/v1.8.1

Please share your log file whenever you have time, and hopefully we can find the root cause :) the log file is called `beatbind.log`

Also in the meantime, you can try installing a previous version to see if it works

**Comment by Iowerth** [comment]
v1.8.1 - I can't start program now because my browser (Firefox) gives me an error like "Unable to connect - can't establish connection with localhost:XXXXXX". Do I need to open port (Inbound Rules) in Windows Firewall? Yesterday I opened this port, but later I disabled this rule and BB worked fine.

PS: please make a feature to always show BB in a system tray as I was trying to understand why I can't delete log file (to start logging from a clear point) - and found that BB was running but only visible in Task Manager.

**Comment by justinknguyen** [comment]
@Iowerth good to see it's working for you now! 

The BeatBind process should always show in the system tray if it's running, so that sounds like a bug. When I press `Quit` on the system tray icon, the process is gone from my Task Manager, so I'll need to monitor this.

**Comment by Iowerth** [comment]
Yes, it is. But I'm about described situation - for example, when some error appear and BB not in tray (because it not fully started) but only in Task Manager.

**Comment by justinknguyen** [comment]
oh I see, I'll fix that in the next release, thanks for reporting it!
