### ISSUE TITLE
Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by Iowerth** [justinknguyen/BeatBind#21]
Hello. Latest version 1.8.3. Windows 10 x64 22H2 19045.4894.

Today Windows Defender moved BeatBind.exe to quarantine with this:
```
Trojan:Win32/Wacatac.B!ml

file: C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\BeatBind.lnk

file: C:\Windows\System32\Tasks\BeatBind->(UTF-16LE)

file: D:\Downloads\BeatBind\BeatBind.exe
regkey: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tasks\{DE0F78BC-35F5-4730-A9AB-450B59302F6D}
regkey: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tree\BeatBind
startup: C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\BeatBind.lnk
taskscheduler: C:\Windows\System32\Tasks\BeatBind
```

**Comment by Iowerth** [comment]
https://www.virustotal.com/gui/file/dc23ff7638b5a4d498afd3dce819e2bde2435a0e73b0d20bf65508a774cd790d

![изображение](https://github.com/user-attachments/assets/2ab77ac2-3ed1-435b-a246-7deeed8204b0)

**Comment by justinknguyen** [comment]
yea since this program is written in Python, and even using nuitka to recompile it to C, Windows sometimes false flags it. I'll try recompiling the app after work, which can help sometimes, but it's best to just exclude the folder from your antivirus. You can also try compiling it yourself

**Comment by Iowerth** [comment]
Yes I can, but others maybe not. Think it would be better to make .exe without this issue.

**Comment by justinknguyen** [comment]
updated the release details with more info
