### ISSUE TITLE
Hotkeys are working while they are not assigned

### ISSUE THREAD

**Issue by Iowerth** [justinknguyen/BeatBind#23]
**Description:**
I have all hotkeys assigned to Ctr+Alt+Shift+SomeButton. When I'm using them then all is fine. But if I use another button (which is not assigned anywhere) then it works like it assigned. In my case pressing Up or Down (without any modifiers) causes Play or Stop respectively. Maybe this is because of error in a log "ERROR - Error occured when updating the startup registry key".

**Steps To Reproduce:**
Described above.

**Expected behavior:**
Only assigned hotkeys must work.

**Screenshots:**
![1](https://github.com/user-attachments/assets/e16059dc-fd46-44ee-a238-606e4e68464f)

**Environment:**
 - Windows 10 x64 22H2 19045.4894
 - BeatBind Version1.8.3

**Log File:**
Newly created log to reproduce an issue.
[beatbind.log](https://github.com/user-attachments/files/17175923/beatbind.log)

**Comment by justinknguyen** [comment]
From your screenshot, Play and Pause are assigned to Up and Down respectively, so pressing Up or Down will trigger them. If you want it so Play and Pause aren't triggered, you have to delete Up and Down from the input fields, like the other hotkeys to the right.

I guess it can be a little confusing, and I plan on updating the UI so it's easier to manage hotkeys

**Comment by justinknguyen** [comment]
you can ignore that error btw. I'll fix it later so it's not shown if Start on Windows startup is false

**Comment by Iowerth** [comment]
Omg, I thought that it all works only with modifiers 😂 Thanks!

> I guess it can be a little confusing, and I plan on updating the UI so it's easier to manage hotkeys

This would be great ;)
