### ISSUE TITLE
Port 8888 is already in use

### ISSUE THREAD

**Issue by SteveSobka** [justinknguyen/BeatBind#3]
I use another program called SimHubDash that also runs a local process on port 8888.  Is there any way to change the port without having to edit the source code and re-compile?

Error message:
This localhost page can’t be found
No webpage was found for the web address: http://localhost:8888/callback?code=xxxxxxxx......

**Comment by justinknguyen** [comment]
Sure, I'll just add another version to the release with that option

**Comment by justinknguyen** [comment]
Added the port field in v1.2.0 

https://github.com/justinknguyen/BeatBind/releases/tag/v1.2.0
