### ISSUE TITLE
Not launching on startup.

### ISSUE THREAD

**Issue by N72826** [justinknguyen/BeatBind#5]
**Describe the bug**
Beatbind doesn't launch on startup despite the registry key possessing the correct path, the task being enabled in the startup tab in task manager, and startup set to true in the config json.

**To Reproduce**
Not really applicable because I'm not getting an error message but:
1. Launch Beatbind
2. Tick "Start on Windows startup" and "Start minimized"
3. Click "Save" 
4. Restart PC
5. Beatbind doesn't start with windows

**Expected behavior**
It should launch on startup. 

**Screenshots**
From `config.json` 
![image](https://github.com/justinknguyen/BeatBind/assets/21070431/867699f8-1b0a-4a6a-ab7b-81022e3e3e00)

From the registry key that holds the path to the executable:
![image](https://github.com/justinknguyen/BeatBind/assets/21070431/d09379fa-02ac-41c0-9da6-3fa71c491a37)

From task manager>startup tab:
![image](https://github.com/justinknguyen/BeatBind/assets/21070431/5e38a6e2-7957-43e6-a605-11753acf7252)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise LTSC
 - Version: 21H2

**Additional context**
N/A but even though this feature isn't functioning correctly at the moment, I am grateful that you created this utility.

**Comment by justinknguyen** [comment]
Which version are you currently using, and has it ever launched on startup correctly before?

To confirm, the icon isn't showing up in your system tray icons?
![image](https://github.com/justinknguyen/BeatBind/assets/20637584/900c5598-39fc-4aa5-8f32-3ad63d7e9dea)

**Comment by N72826** [comment]
Oh didn't expect you to reply so fast I would have hit you back sooner.
I was using version 1.1.0 and no it never correctly launched on startup. The icon appeared in the tray and I could use my hotkeys but I would have to manually launch it every time after restarting.

I just downloaded the latest version (1.2.0) and I will let you know if everything is fixed now. For some reason, 1.2.0 doesn't appear under "Latest Release" on the homepage of the repo unless I click all releases.
![image](https://github.com/justinknguyen/BeatBind/assets/21070431/4fed88d9-5554-4ebb-8c6f-b754733ca09d)

**Comment by justinknguyen** [comment]
v1.2.0 isn't as user friendly and it's only necessary for some people that are already using port 8888, so I didn't mark it as a latest release.

So it does start in the tray when you turn on your PC? That's the intended behaviour of "Start minimized" as it starts minimized to tray. If you want the window to show, you have to uncheck "Start minimized"

**Comment by justinknguyen** [comment]
You double checked that the path in the registry key is the same path that the exe is in currently, right? Do you have windows fast startup enabled?

**Comment by N72826** [comment]
I'm at work right now so I can't check if I have fast startup enabled but I already tried manually adding it to startup by placing a shortcut in the startup folder.
I'll keep you updated.

**Comment by justinknguyen** [comment]
hmm that's super odd. Maybe it's just a Windows fast startup issue, but just to make sure, you're copying and pasting in a _shortcut_ to the exe file right? It seems like you downloaded the .zip folder of the release, so what's in the Startup folder has to be the shortcut, not the exe file itself.

Have you tried downloading the standalone exe file instead?

**Comment by justinknguyen** [comment]
Have you tried with other apps in the Startup folder and do they work?

**Comment by N72826** [comment]
Yes, I have plenty of startup programs that work just fine.
