### ISSUE TITLE
opening, then immediately closing

### ISSUE THREAD

**Issue by eskiee** [justinknguyen/BeatBind#6]
**Describe the bug**
Downloaded and working great yesterday. Today, did not launch when PC turned on. Was not displaying in system tray as it was yesterday either. Opened from the file location, and app would open then immediately close. Tried many times, and finally was able to click in the app fast enough, but it would close just a moment after. Hotkeys that were working yesterday are not working either.

**To Reproduce** 
1. Go to app
2. Click on open/run
3. Scroll down to '....' (N/A)

**Expected behavior**
Able to launch the app on startup, or even just when I open it as normal.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v1.1.0

**Comment by justinknguyen** [comment]
Sounds like the config file got corrupt somehow. Try deleting the folder:

- Press Win+R to bring up the "Run" menu, or type in "Run" within your Windows search bar.

- Enter the following in the "Open" input field:
%appdata%

- Your information is stored locally within the .../AppData/Roaming/.beatbind folder.

**Comment by eskiee** [comment]
That did the trick! Working fine now. Thank you!

**Comment by lexakami** [comment]
I'm also getting this issue, and when I delete the `.beatbind` folder it does work but just seems to break again when I restart my computer and I have to re enter the details every time.

Tried both the exe directly and the zip folder, but both act the same. Also thought maybe it could be a port conflict, but changed it and still the same. Also tried disabling it launching on start up, but that doesn't seem to make a difference either... 😭

**Comment by justinknguyen** [comment]
> I'm also getting this issue, and when I delete the `.beatbind` folder it does work but just seems to break again when I restart my computer and I have to re enter the details every time.
> 
> 
> 
> Tried both the exe directly and the zip folder, but both act the same. Also thought maybe it could be a port conflict, but changed it and still the same. Also tried disabling it launching on start up, but that doesn't seem to make a difference either... 😭

yea, I'll see if I can push a fix this weekend for it

**Comment by justinknguyen** [comment]
> I'm also getting this issue, and when I delete the `.beatbind` folder it does work but just seems to break again when I restart my computer and I have to re enter the details every time.
> 
> Tried both the exe directly and the zip folder, but both act the same. Also thought maybe it could be a port conflict, but changed it and still the same. Also tried disabling it launching on start up, but that doesn't seem to make a difference either... 😭

this should be fixed now. Let me know if it doesn't work still

https://github.com/justinknguyen/BeatBind/releases/tag/v1.3.0

**Comment by lexakami** [comment]
Thanks for addressing it so quickly! 

I replaced the program, but now it seems to erase all of my settings when my computer restarts for some reason.

**Comment by justinknguyen** [comment]
> Thanks for addressing it so quickly!
> 
> I replaced the program, but now it seems to erase all of my settings when my computer restarts for some reason.
> 
> Let me know if you'd like me to create a new issue for this.

hmm, I'm not getting the same problem. Are you moving the .exe file out of the folder by any chance? The .exe file needs to be in the same directory as your config settings file `beatbind-config.json` to read it. If you open your config file, are your settings saved in it?

**Comment by lexakami** [comment]
It's just in my Program files and I didn't move the exe out of the folder. I can't seem to find the `beatbind-config.json` file at all though so that might be the issue, not sure why it's not there..

I just have the default Windows defender, have added an exclusion now just in case but it doesn't seem to make a difference.

**Comment by justinknguyen** [comment]
> It's just in my Program files and I didn't move the exe out of the folder. I can't seem to find the `beatbind-config.json` file at all though so that might be the issue, not sure why it's not there..
> 
> I just have the default Windows defender, have added an exclusion now just in case but it doesn't seem to make a difference.

the config file gets created when you press on 'Save', does it not create one when you press on save?

**Comment by lexakami** [comment]
It doesn't seem to, no 🤔

**Comment by justinknguyen** [comment]
> It doesn't seem to, no 🤔 assuming it should appear in the root directory of the app

yea, it should be created where the .exe is. You can try manually creating the file instead. Here's what the content should look like

```
{
    "startup": false,
    "minimize": false,
    "client_id": "",
    "client_secret": "",
    "port": "8888",
    "device_id": "",
    "volume": "5",
    "hotkeys": {
        "play/pause": "control+alt+shift+p",
        "prev_track": "control+alt+shift+left",
        "next_track": "control+alt+shift+right",
        "volume_up": "control+alt+shift+up",
        "volume_down": "control+alt+shift+down",
        "mute": "control+alt+shift+space"
    }
}
```

**Comment by justinknguyen** [comment]
> It doesn't seem to, no 🤔 assuming it should appear in the root directory of the app

Just moved mine to the Program Files folder also and you're right, it doesn't save if it's placed in that folder. I'll see if I can push a fix soon

**Comment by lexakami** [comment]
Ahh right sorry I should have tried that before! It works perfectly now, thank you!!
