### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by themis21l** [justinknguyen/BeatBind#7]
I downloaded your program, i did everything you said but it didnt work, when i press the hotkey it doesnt do anything. Does it need to download something else besides your program ?

**Comment by justinknguyen** [comment]
Email me a screenshot of your settings to justinkn.dev@gmail.com

Also confirm if the app's icon is in your system tray after pressing `Start & Close`

**Comment by justinknguyen** [comment]
Resolved by download v1.2.0 and using a custom port
