### ISSUE TITLE
Usage WITHOUT Premium

### ISSUE THREAD

**Issue by AmazingTesterRocks** [justinknguyen/BeatBind#9]
Would highly appreciate it if you could make the app run without premium AKA without spotify's api for free users

**Comment by justinknguyen** [comment]
I sent in a request for my app to be approved. Once it's approved then I think I can make it so this works without premium, but it's been months of waiting so far

**Comment by AmazingTesterRocks** [comment]
Ohh, do let me know once it gets approve. Also send in a new request if possible as there may be a chance that it was ghosted

**Comment by justinknguyen** [comment]
As a follow up, I will not be changing this to work without the API so it can work without premium. You can find a lot of AHK scripts or some other apps online that run locally, but they always break because of changes to the desktop app.

Here's a repo I found that runs locally

https://github.com/mavvos/SpotifyGlobal

**Comment by justinknguyen** [comment]
Looks like this won't work for free users even with the extended quota mode. The endpoints used in Spotify's Web API only works for premium users, so it's not possible for this app to work for free users. I'll close this ticket now

**Comment by AmazingTesterRocks** [comment]
Is there not anything else that can be done? the one you suggested earlier was already tested by me and it doesn't work (supposedly because it only runs on win10)

**Comment by justinknguyen** [comment]
> Is there not anything else that can be done? the one you suggested earlier was already tested by me and it doesn't work (supposedly because it only runs on win10)

Sorry, I can't do anything about it. Spotify locked some endpoints to only Premium users, and this app uses those endpoints. Here's an example of one https://developer.spotify.com/documentation/web-api/reference/start-a-users-playback

You'll see that it says "This API only works for users who have Spotify Premium." at the top.

As for the other app not working, it's the reason why I created this app to use Spotify's Web API. Making it run locally seems to always break sooner or later, so as long as Spotify has their API for the public to use, then this will always work

**Comment by AmazingTesterRocks** [comment]
Even tho I am outta alternatives, the day 1 I created this ticket was the day toastify broke and it was working for a long time even after this app you created. any chance you could attempt and fix it?  I would gladly appreciate it 💯

**Comment by justinknguyen** [comment]
> 
> 
> Even tho I am outta alternatives, the day 1 I created this ticket was the day toastify broke and it was working for a long time even after this app you created. any chance you could attempt and fix it?  I would gladly appreciate it 💯 
> 
> As of now, it is giving an error saying "Couldn't find Spotify main window. Try to start Spotify manually before launching Toastify"

Sorry, I don't have time to fix another developer's app, especially since I have my own app.

If you manage to fix it or find someone else who can, it will stop working sooner or later anyways. I've gone through a handful of apps over the years that ends up not working due to Spotify updates and changes.
